spring.application.name=appdomirest

# Logging
logging.level.root=INFO
logging.level.com.josepinodev.appdomirest=DEBUG
logging.level.org.thymeleaf=WARN
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# MySQL Connection
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:appdomirest}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:Kristoff_Mora26123009}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

